### ISSUE TITLE
Mask/filter issue

### ISSUE THREAD

**Issue by CasperEngl** [bitkidd/DigitalOcean-Spaces-Sync#11]
Reference: #2 

It's happening for me with DO Spaces Sync 2.0.2.1 and Elementor 2.2.5 + Elementor Pro 2.1.10
My regex is `/^.*\.(jpg|jpeg|png|gif|ico|svg|pdf|doc|docx|ppt|pptx|pps|ppsx|odt|xls|xlsx|psd|mp3|m4a|ogg|wav|mp4|m4v|mov|wmw|avi|mpg|ogv|3gp|3g2)$/i`
The regex is basically just a copy of all default allowed files in WordPress upload with the exception of SVG which I've added.

`https://domain.tld/wp-content/uploads/elementor/css/*.css` files are rewritten to `https://ams3.digitaloceanspaces.com/domain.tld/elementor/css/*.css`

Is the regex being applied on URL rewrites on the frontend?

**Comment by Dibbyo456** [comment]
You may fix it via is_user_logged_in() filter

**Comment by nodakjones** [comment]
This issue makes it impossible to use elementor with DO spaces sync.  Is there a solution to this problem so that the css files aren't being rewritten to the spaces url?

**Comment by autoferrit** [comment]
I have this issue as well. Since my theme is more tied to elementor, this makes me not able to use DO spaces sync.

**Comment by keeross** [comment]
Will try to fix it this weekend

**Comment by bmizoguchi** [comment]
Any updates?

**Comment by nodakjones** [comment]
Yes, would love to get this fixed!  Any update?

**Comment by nodakjones** [comment]
It seems like the regex is still not being applied on URL rewrites?  Any thoughts on how this might be fixed?
