### ISSUE TITLE
Wordpress Multisite

### ISSUE THREAD

**Issue by Akshay-Sharda** [bitkidd/DigitalOcean-Spaces-Sync#18]
On setting this up for multisite

it Does upload the file to the DO Spaces
But Still Shows error

http://prntscr.com/m0v8ou
____

but it did upload in DO Spaces
http://prntscr.com/m0v8yi
~~~

and in general on opening media library displays the following :-
http://prntscr.com/m0v8ju

~~~~~~

the following is the setting that i am using

http://prntscr.com/m0v9ap

**Comment by keeross** [comment]
Not sure if it still the case, could you please update the plugin and try again. I use it with a multisite wordpress and it works just fine.

**Comment by ronaldoscotti** [comment]
I'm also having this problem. The image is uploaded to the Space but it shows me an error message on the media library.
