### ISSUE TITLE
Unable to upload plugins via zip file

### ISSUE THREAD

**Issue by Lastik** [bitkidd/DigitalOcean-Spaces-Sync#30]
How reproduce:
1) mark both
-Store files only in the cloud and delete after successful upload. In that case file will be removed from your server after being uploaded to cloud storage, that saves you space.
-Delete file from cloud storage as soon as it was removed from your library.
2)Try to install any other plugin via zip file upload (manual from file system).

This will give you "Download failed. A valid URL was not provided." error.
Disable the plugin and everything is working back again.

**Comment by Lastik** [comment]
Some more info. I found out that zip file while installing plugin is for some reason also uploading to digitalocean spaces cloud instead of server.

**Comment by eimpacteric** [comment]
Same problem here
