### ISSUE TITLE
Regenerate Thumbnails

### ISSUE THREAD

**Issue by karlproctor** [bitkidd/DigitalOcean-Spaces-Sync#31]
Using the wp cli command or the Regenerate Thumbnails plugin to regenerate images doesn't work when using this plugin. Is there a way to do this when using this plugin?

**Comment by opicron** [comment]
I made an script that checks if the file is present locally. If not it downloads the file and then the regenerate thumbnail works fine.

**Comment by opicron** [comment]
Something like this should work for you..

`add_filter ( 'get_attached_file', 'my_get_attached_file', 1, 2);
function my_get_attached_file( $file, $attachment_id )
{	
		if ( defined( 'WP_CLI' ) && WP_CLI ) 
		{		
			$source = wp_get_attachment_url( $attachment_id );
			$target = $file;

			//if meta data is set append .original to $source
			$optimized = get_post_meta($attachment_id, '_typist_tech_image_optimized', true);

			//if ($optimized)
			//	$source .= '.original';

			//download file if not exists or if original has been backed up before
			if ( ! file_exists ( $target ) /*|| $optimized*/ )
			{
				WP_CLI::log( 'Download original from Digital Ocean Spaces' );
				WP_CLI::debug( WP_CLI::colorize( '%B====> %nTarget: '.$target ) );

				if ($optimized)
				{
					WP_CLI::debug( WP_CLI::colorize( '%B====> %nSource: '.$source.'%R.original%n' ) );
					file_put_contents($target, fopen($source.'.original', 'r'));
				}

				if ( ! file_exists ( $target ) || ! $optimized || filesize ( $target ) == 0 )
				{
					WP_CLI::debug( WP_CLI::colorize( '%B====> %nSource: '.$source ) );
					file_put_contents($target, fopen($source, 'r'));
				}


			}
		}
	
	return $file;
}`
