### ISSUE TITLE
Edited images not being saved to Spaces

### ISSUE THREAD

**Issue by vgibara** [bitkidd/DigitalOcean-Spaces-Sync#42]

**Comment by opicron** [comment]
I had the same issue-- but it is actually an cache issue of Digital Ocean Spaces. I use s3cmd script to reset the cache of changed images.

**Comment by vgibara** [comment]
I made a couple of tests and the edited file was not saved to DO Spaces at all. It stayed on the folder on the server, but never gets uploaded to DO.

**Comment by opicron** [comment]
Ok thats odd. Ive been using this script three years. Never had an issue with not uploading.

Did you by any chance try to re-upload the same file multiple times? I noticed DO is a bit strict with that.
