### ISSUE TITLE
How safe is it to remove this plugin?

### ISSUE THREAD

**Issue by mkanakis** [bitkidd/DigitalOcean-Spaces-Sync#52]
Hi @bitkidd ,

Thanks for providing this awesome plugin and all the work.

I see that there are no milestones, nor development timelines or ongoing development and I am bit worried as for the impact this plugin might have for future Wordpress and plugin updates (i.e., causing major issues).

Do you see any releases in the future? Or have you dropped development completely?

In any case, what happens when you delete the plugin from a website? Does it rewrite all urls back to defaults and leaves no trace? Or is it left hanging in there?

Kind regards,
Marios.

**Comment by bitkidd** [comment]
Hey!
I still use the plugin on a project of mine and it works just fine overall.
But I don't plan an update and basically plan to archive it.

You can safely remove the plugin, but before this you have to leave `Full URL-path to files` field blank and `Save` the config, this will allow WordPress to serve files from a local server.

Thank you.
