### ISSUE TITLE
Slow DO upload - Add option to do DO upload in different thread (cron)

### ISSUE THREAD

**Issue by MrNghia123** [bitkidd/DigitalOcean-Spaces-Sync#6]
Hi,
Currently the plugin seems to do DO upload in the same process of uploading file to wordpress. This can significantly slow down the uploads.
Adding the option to "move" the DO upload job to another thread (or wp cron) will be very helpful.
Regards,
Nghia Huynh

**Comment by keeross** [comment]
Thinking on it, probably will add in 2-3 weeks.

**Comment by luizjr** [comment]
> Thinking on it, probably will add in 2-3 weeks.

Have done?
How do I sync existing files?

**Comment by opicron** [comment]
I am facing the same issue. It would be _great_ to task it a minute or two later (configurable).
